
package com.mcms.entities;

// Generated Jan 9, 2011 8:08:10 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	// Fields    

	private long id;

	private String userid;

	private String password;

	private String name;

	private String ecode;

	private String compCode;

	private Integer userStatusId;
	
	private Integer userType;

	private String locCode;
	
	private String primaryLocCode;
	
	private String caCode;
	
	private String branchCode;
	
	private String zoneCode;
	
	private String regCode;

	private Integer wrongPwdCnt;

	private String createdBy;

	private Date creationDtm;

	private String updatedBy;

	private Date updationDtm;
	
	private String collectorId;
	
	private Date lastLoginDtm;
	
	private String collectionUnitCode;
	
	private long collectionUnitId;
	
	private String vertical;
	
	private String tpin; 
	
	private String stateId;
	
	private String reportUserId;
	
	private String cityCode;
	
	private String unitType;
	
	private String cashId;
	
	private Date passWordChangeDtm;
	
	private Date lastLogoutDtm;
	
	private String remarksForUserStatusChange;
	
	private Date blockedDtm;
	
	private String blockedBy;
	
	private String employeeNumber;

	//private String macId;
	
	// Constructors

	public Date getBlockedDtm() {
		return blockedDtm;
	}

	public void setBlockedDtm(Date blockedDtm) {
		this.blockedDtm = blockedDtm;
	}

	public String getBlockedBy() {
		return blockedBy;
	}

	public void setBlockedBy(String blockedBy) {
		this.blockedBy = blockedBy;
	}

	/** default constructor */
	public Users() {
	}

	/** minimal constructor */
	public Users(long id, String userid, String password, String ecode,
			String compCode) {
		this.id = id;
		this.userid = userid;
		this.password = password;
		this.ecode = ecode;
		this.compCode = compCode;
	}

	/** full constructor */
	public Users(long id, String userid, String password, String name,
			String ecode, String compCode, Integer userStatusId,
			String locCode, Integer wrongPwdCnt, String createdBy,
			Date creationDtm, String updatedBy, Date updationDtm,String collectionUnitCode, long collectionUnitId,String vertical, String tpin) {
		this.id = id;
		this.userid = userid;
		this.password = password;
		this.name = name;
		this.ecode = ecode;
		this.compCode = compCode;
		this.userStatusId = userStatusId;
		this.locCode = locCode;
		this.wrongPwdCnt = wrongPwdCnt;
		this.createdBy = createdBy;
		this.creationDtm = creationDtm;
		this.updatedBy = updatedBy;
		this.updationDtm = updationDtm;
		this.collectionUnitCode = collectionUnitCode;
		this.collectionUnitId=collectionUnitId;
		this.vertical = vertical;
		this.tpin = tpin;
	}

	// Property accessors
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEcode() {
		return this.ecode;
	}

	public void setEcode(String ecode) {
		this.ecode = ecode;
	}

	public String getCompCode() {
		return this.compCode;
	}

	public void setCompCode(String compCode) {
		this.compCode = compCode;
	}

	public Integer getUserStatusId() {
		return this.userStatusId;
	}

	public void setUserStatusId(Integer userStatusId) {
		this.userStatusId = userStatusId;
	}

	public String getLocCode() {
		return this.locCode;
	}

	public void setLocCode(String locCode) {
		this.locCode = locCode;
	}

	public Integer getWrongPwdCnt() {
		return this.wrongPwdCnt;
	}

	public void setWrongPwdCnt(Integer wrongPwdCnt) {
		this.wrongPwdCnt = wrongPwdCnt;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreationDtm() {
		return this.creationDtm;
	}

	public void setCreationDtm(Date creationDtm) {
		this.creationDtm = creationDtm;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdationDtm() {
		return this.updationDtm;
	}

	public void setUpdationDtm(Date updationDtm) {
		this.updationDtm = updationDtm;
	}

	public String getCollectorId() {
		return collectorId;
	}

	public void setCollectorId(String collectorId) {
		this.collectorId = collectorId;
	}

	public String getRegCode() {
		return regCode;
	}

	public void setRegCode(String regCode) {
		this.regCode = regCode;
	}

	public Integer getUserType() {
		return userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	public String getCaCode() {
		return caCode;
	}

	public void setCaCode(String caCode) {
		this.caCode = caCode;
	}

	public String getBranchCode() {
		return branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	public String getZoneCode() {
		return zoneCode;
	}

	public void setZoneCode(String zoneCode) {
		this.zoneCode = zoneCode;
	}

	public Date getLastLoginDtm() {
		return lastLoginDtm;
	}

	public void setLastLoginDtm(Date lastLoginDtm) {
		this.lastLoginDtm = lastLoginDtm;
	}

	public String getPrimaryLocCode() {
		return primaryLocCode;
	}

	public void setPrimaryLocCode(String primaryLocCode) {
		this.primaryLocCode = primaryLocCode;
	}

	public String getCollectionUnitCode() {
		return collectionUnitCode;
	}

	public void setCollectionUnitCode(String collectionUnitCode) {
		this.collectionUnitCode = collectionUnitCode;
	}

	public String getVertical() {
		return vertical;
	}

	public void setVertical(String vertical) {
		this.vertical = vertical;
	}

	public String getTpin() {
		return tpin;
	}

	public void setTpin(String tpin) {
		this.tpin = tpin;
	}

	public String getStateId() {
		return stateId;
	}

	public void setStateId(String stateId) {
		this.stateId = stateId;
	}

	public String getReportUserId() {
		return reportUserId;
	}

	public void setReportUserId(String reportUserId) {
		this.reportUserId = reportUserId;
	}

	public String getCityCode() {
		return cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	public String getUnitType() {
		return unitType;
	}

	public void setUnitType(String unitType) {
		this.unitType = unitType;
	}

	public String getCashId() {
		return cashId;
	}

	public void setCashId(String cashId) {
		this.cashId = cashId;
	}

	public Date getPassWordChangeDtm() {
		return passWordChangeDtm;
	}

	public void setPassWordChangeDtm(Date passWordChangeDtm) {
		this.passWordChangeDtm = passWordChangeDtm;
	}

	public Date getLastLogoutDtm() {
		return lastLogoutDtm;
	}

	public void setLastLogoutDtm(Date lastLogoutDtm) {
		this.lastLogoutDtm = lastLogoutDtm;
	}

	public long getCollectionUnitId() {
		return collectionUnitId;
	}

	public void setCollectionUnitId(long collectionUnitId) {
		this.collectionUnitId = collectionUnitId;
	}

	public String getRemarksForUserStatusChange() {
		return remarksForUserStatusChange;
	}

	public void setRemarksForUserStatusChange(String remarksForUserStatusChange) {
		this.remarksForUserStatusChange = remarksForUserStatusChange;
	}

	public String getEmployeeNumber() {
		return employeeNumber;
	}

	public void setEmployeeNumber(String employeeNumber) {
		this.employeeNumber = employeeNumber;
	}

	/*public String getMacId() {
		return macId;
	}

	public void setMacId(String macId) {
		this.macId = macId;
	}	
	*/
	
}
