
package com.mcms.entities;

import java.util.Date;

// Generated Jan 4, 2011 11:35:20 PM by Hibernate Tools 3.2.0.beta8

/**
 * BankMst generated by hbm2java
 */
public class EmpMst implements java.io.Serializable {

	// Fields
	private long id;
	
	private String userid;
	
	private String userName;

	private String mobileNo;

	private String email;
	
	private boolean active;
	
	private Date updationDtm;


	// Constructors

	/** default constructor */
	public EmpMst() {
	}

	/** minimal constructor */
	public EmpMst(long id,String userid, String userName, String mobileNo) {
		this.id=id;
		this.userid = userid;
		this.userName = userName;
		this.mobileNo = mobileNo;
	}

	/** full constructor */
	public EmpMst(String userid, String userName, String mobileNo,String email) {
		this.userid = userid;
		this.userName = userName;
		this.mobileNo = mobileNo;
		this.email = email;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getMobileNo() {
		return mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public boolean isActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Date getUpdationDtm() {
		return updationDtm;
	}

	public void setUpdationDtm(Date updationDtm) {
		this.updationDtm = updationDtm;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	// Property accessors
		
}
