
package com.mcms.entities;

// Generated Jan 8, 2011 3:02:09 PM by Hibernate Tools 3.2.0.beta8

/**
 * RoleMst generated by hbm2java
 */
public class RoleMst implements java.io.Serializable {

	// Fields    

	private long id;

	private int roleId;

	private String roleName;
	
	private String vertical;
	
	private String reportType;
	
	private int reportUserRole;
	
	private int operation1;
	
	private int operation2;
	private int operation3;
	private int operation4;
	private int operation5;
	private int operation6;
	private int operation7;
	private int operation8;
	private int operation9;
	private int operation10;
	private int operation11;
	private int operation12;
	private int operation13;
	private int operation14;
	private int operation15;
	private int operation16;
	private int operation17;
	private int operation18;
	private int operation19;
	private int operation20;
	private int operation21;
	private int operation22;
	private int operation23;
	private int operation24;
	private int operation25;
	private int operation26;
	
	private int operation27;
	private int operation28;
	private int operation29;
	private int operation30;
	private int operation31;
	private int operation32;
	private int operation33;
	private int operation34;
	private int operation35;
	private int operation36;
	private int operation37;
	private int operation38;
	private int operation39;
	private int operation40;
	private int operation41;
	private int operation42;
	private int operation43;
	private int operation44;
	private int operation46;
	
	
	
	// Constructors

	public int getOperation44() {
		return operation44;
	}

	public void setOperation44(int operation44) {
		System.out.println("Hello--------------"+operation44);
		this.operation44 = operation44;
	}

	public int getOperation42() {
		return operation42;
	}

	public void setOperation42(int operation42) {
		this.operation42 = operation42;
	}

	public int getOperation43() {
		return operation43;
	}

	public void setOperation43(int operation43) {
		this.operation43 = operation43;
	}

	/** default constructor */
	public RoleMst() {
	}

	/** full constructor */
	public RoleMst(long id, int roleId, String roleName,String vertical,String reportType,int reportUserRole) {
		this.id = id;
		this.roleId = roleId;
		this.roleName = roleName;
		this.vertical = vertical;
		this.reportType = reportType;
		this.reportUserRole = reportUserRole;
	}

	// Property accessors
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public int getOperation3() {
		return operation3;
	}

	public void setOperation3(int operation3) {
		System.out.println("OPERATN 3......."+operation3);
		this.operation3 = operation3;
	}

	public int getOperation4() {
		return operation4;
	}

	public void setOperation4(int operation4) {
		System.out.println("OPERATN 4......."+operation4);
		this.operation4 = operation4;
	}

	public int getOperation5() {
		return operation5;
	}

	public void setOperation5(int operation5) {
		this.operation5 = operation5;
	}

	public int getOperation6() {
		return operation6;
	}

	public void setOperation6(int operation6) {
		this.operation6 = operation6;
	}

	public int getOperation7() {
		return operation7;
	}

	public void setOperation7(int operation7) {
		this.operation7 = operation7;
	}

	public int getOperation8() {
		return operation8;
	}

	public void setOperation8(int operation8) {
		this.operation8 = operation8;
	}

	public int getOperation9() {
		return operation9;
	}

	public void setOperation9(int operation9) {
		this.operation9 = operation9;
	}

	public int getOperation10() {
		return operation10;
	}

	public void setOperation10(int operation10) {
		this.operation10 = operation10;
	}

	public int getOperation11() {
		return operation11;
	}

	public void setOperation11(int operation11) {
		this.operation11 = operation11;
	}

	public int getOperation12() {
		return operation12;
	}

	public void setOperation12(int operation12) {
		this.operation12 = operation12;
	}

	public int getOperation13() {
		return operation13;
	}

	public void setOperation13(int operation13) {
		this.operation13 = operation13;
	}

	public int getOperation14() {
		return operation14;
	}

	public void setOperation14(int operation14) {
		this.operation14 = operation14;
	}

	public int getOperation15() {
		return operation15;
	}

	public void setOperation15(int operation15) {
		this.operation15 = operation15;
	}

	public int getOperation16() {
		return operation16;
	}

	public void setOperation16(int operation16) {
		this.operation16 = operation16;
	}

	public int getOperation17() {
		return operation17;
	}

	public void setOperation17(int operation17) {
		this.operation17 = operation17;
	}

	public int getOperation18() {
		return operation18;
	}

	public void setOperation18(int operation18) {
		this.operation18 = operation18;
	}

	public int getOperation19() {
		return operation19;
	}

	public void setOperation19(int operation19) {
		this.operation19 = operation19;
	}

	public int getOperation20() {
		return operation20;
	}

	public void setOperation20(int operation20) {
		this.operation20 = operation20;
	}

	public int getOperation21() {
		return operation21;
	}

	public void setOperation21(int operation21) {
		this.operation21 = operation21;
	}

	public int getOperation22() {
		return operation22;
	}

	public void setOperation22(int operation22) {
		this.operation22 = operation22;
	}

	public int getOperation23() {
		return operation23;
	}

	public void setOperation23(int operation23) {
		this.operation23 = operation23;
	}

	public int getOperation24() {
		return operation24;
	}

	public void setOperation24(int operation24) {
		this.operation24 = operation24;
	}

	public int getOperation25() {
		return operation25;
	}

	public void setOperation25(int operation25) {
		this.operation25 = operation25;
	}

	public int getOperation26() {
		return operation26;
	}

	public void setOperation26(int operation26) {
		this.operation26 = operation26;
	}

	public int getOperation27() {
		return operation27;
	}

	public void setOperation27(int operation27) {
		this.operation27 = operation27;
	}

	public int getOperation28() {
		return operation28;
	}

	public void setOperation28(int operation28) {
		this.operation28 = operation28;
	}

	public int getOperation29() {
		return operation29;
	}

	public void setOperation29(int operation29) {
		this.operation29 = operation29;
	}

	public int getOperation30() {
		return operation30;
	}

	public void setOperation30(int operation30) {
		this.operation30 = operation30;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getVertical() {
		return vertical;
	}

	public void setVertical(String vertical) {
		this.vertical = vertical;
	}

	public String getReportType() {
		return reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	public int getReportUserRole() {
		return reportUserRole;
	}

	public void setReportUserRole(int reportUserRole) {
		this.reportUserRole = reportUserRole;
	}

	public int getOperation1() {
		return operation1;
	}

	public void setOperation1(int operation1) {
		System.out.println("Hello.............."+operation1);
		this.operation1 = operation1;
	}

	public int getOperation2() {
		return operation2;
	}

	public void setOperation2(int operation2) {
		this.operation2 = operation2;
	}

	public int getOperation31() {
		return operation31;
	}

	public void setOperation31(int operation31) {
		this.operation31 = operation31;
	}

	public int getOperation32() {
		return operation32;
	}

	public void setOperation32(int operation32) {
		this.operation32 = operation32;
	}

	public int getOperation33() {
		return operation33;
	}

	public void setOperation33(int operation33) {
		this.operation33 = operation33;
	}

	public int getOperation34() {
		return operation34;
	}

	public void setOperation34(int operation34) {
		this.operation34 = operation34;
	}

	public int getOperation35() {
		return operation35;
	}

	public void setOperation35(int operation35) {
		this.operation35 = operation35;
	}

	public int getOperation36() {
		return operation36;
	}

	public void setOperation36(int operation36) {
		this.operation36 = operation36;
	}

	public int getOperation37() {
		return operation37;
	}

	public void setOperation37(int operation37) {
		this.operation37 = operation37;
	}

	public int getOperation38() {
		return operation38;
	}

	public void setOperation38(int operation38) {
		this.operation38 = operation38;
	}

	public int getOperation39() {
		return operation39;
	}

	public void setOperation39(int operation39) {
		this.operation39 = operation39;
	}

	public int getOperation40() {
		return operation40;
	}

	public void setOperation40(int operation40) {
		this.operation40 = operation40;
	}

	public int getOperation41() {
		return operation41;
	}

	public void setOperation41(int operation41) {
		this.operation41 = operation41;
	}

	public int getOperation46() {
		return operation46;
	}

	public void setOperation46(int operation46) {
		this.operation46 = operation46;
	}



}
