
package com.mcms.entities;

// Generated Jan 16, 2011 4:33:58 PM by Hibernate Tools 3.2.0.beta8

/**
 * UserStatusMst generated by hbm2java
 */
public class UserStatusMst implements java.io.Serializable {

	// Fields    

	private long id;

	private int userStatusId;

	private String userStatus;

	// Constructors

	/** default constructor */
	public UserStatusMst() {
	}

	/** full constructor */
	public UserStatusMst(long id, int userStatusId, String userStatus) {
		this.id = id;
		this.userStatusId = userStatusId;
		this.userStatus = userStatus;
	}

	// Property accessors
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public int getUserStatusId() {
		return this.userStatusId;
	}

	public void setUserStatusId(int userStatusId) {
		this.userStatusId = userStatusId;
	}

	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

}
