
package com.mcms.entities;

// Generated Jan 8, 2011 3:02:09 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * Userhasrole generated by hbm2java
 */
public class Userhasrole implements java.io.Serializable {

	// Fields    

	private long id;

	private String userid;

	private int roleId;

	private Date startDate;

	private Date endDate;

	// Constructors

	/** default constructor */
	public Userhasrole() {
	}

	/** minimal constructor */
	public Userhasrole(long id, String userid, int roleId) {
		this.id = id;
		this.userid = userid;
		this.roleId = roleId;
	}

	/** full constructor */
	public Userhasrole(long id, String userid, int roleId, Date startDate,
			Date endDate) {
		this.id = id;
		this.userid = userid;
		this.roleId = roleId;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	// Property accessors
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
